export const excerciseData = [
    {
        key: 1,
        name: "Chest Press",
        method: "Machine",
        muscle: "Chest",
        photo: "",
    }, 
    {
        key: 2,
        name: "Shoulder Press",
        method: "Machine",
        muscle: "Shoulders",
        photo: "",
    },     
    {
        key: 3,
        name: "Dead Hang",
        method: "Bodyweight",
        muscle: "Back",
        photo: "",
    },     
    {
        key: 4,
        name: "Dip",
        method: "Bodyweight",
        muscle: "Arms",
        photo: "",
    },     
    {
        key: 5,
        name: "Lateral Raise",
        method: "Machine",
        muscle: "Shoulders",
        photo: "",
    }, 
    {
        key: 6,
        name: "Tricep Extension",
        method: "Machine",
        muscle: "Arms",
        photo: "",
    },     
    {
        key: 7,
        name: "Chest Fly",
        method: "Machine",
        muscle: "Chest",
        photo: "",
    },     
    {
        key: 8,
        name: "Incline Bench Press",
        method: "Dumbbell",
        muscle: "Chest",
        photo: "",
    },     
    {
        key: 9,
        name: "Reverse Wrist Curl",
        method: "Dumbbell",
        muscle: "Arms",
        photo: "",
    },     
    {
        key: 10,
        name: "Wrist Curls",
        method: "Dumbbell",
        muscle: "Arms",
        photo: "",
    },     
    {
        key: 11,
        name: "Pull-Up",
        method: "Bodyweight",
        muscle: "Back",
        photo: "",
    },     
    {
        key: 12,
        name: "Back Extension",
        method: "Machine",
        muscle: "Back",
        photo: "",
    },     
    {
        key: 13,
        name: "Rear Delt Fly",
        method: "Machine",
        muscle: "Shoulders",
        photo: "",
    },     
    {
        key: 14,
        name: "Chest Supported Row",
        method: "Machine",
        muscle: "Back",
        photo: "",
    },     
    {
        key: 15,
        name: "Lat Pulldown",
        method: "Machine",
        muscle: "Back",
        photo: "",
    },     
    {
        key: 16,
        name: "Reverse Wrist Curl",
        method: "Barbell",
        muscle: "Arms",
        photo: "",
    },     
    {
        key: 17,
        name: "Preacher Curl",
        method: "Barbell",
        muscle: "Arms",
        photo: "",
    },     
    {
        key: 18,
        name: "Hip Thrust",
        method: "Machine",
        muscle: "Glutes",
        photo: "",
    }, 
    {
        key: 19,
        name: "Seated Calf Raise",
        method: "",
        muscle: "Legs",
        photo: "",
    }, 
    {
        key: 20,
        name: "Leg Press",
        method: "",
        muscle: "Legs",
        photo: "",
    }, 
    {
        key: 21,
        name: "Leg Curl",
        method: "Machine",
        muscle: "Legs",
        photo: "",
    }, 
    {
        key: 22,
        name: "Hip Adductor",
        method: "Machine",
        muscle: "Legs",
        photo: "",
    },     
    {
        key: 23,
        name: "Hip Abductor",
        method: "Machine",
        muscle: "Legs",
        photo: "",
    }, 
    {
        key: 24,
        name: "Leg Extension",
        method: "Machine",
        muscle: "Legs",
        photo: "",
    }, 
    {
        key: 25,
        name: "Abs Crunch",
        method: "Machine",
        muscle: "Core",
        photo: "",
    }, 
    {
        key: 26,
        name: "",
        method: "",
        muscle: "",
        photo: "",
    },
]